name: CI/CD

on:
  workflow_dispatch:
    inputs:
      version-increment:
        default: "patch"
        description: "The version increment (major, minor, patch). Defaults to patch."
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: []
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build artifacts
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build

  bump-version:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm ci
        
      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          milestone: ${{ github.sha }}
          
      - name: Bump version and commit
        run: |
          npm version ${{ github.inputs.version-increment }}
          git add package.json CHANGELOG.md
          git commit -m "Bump version to ${{ github.inputs.version-increment }} ${{ github.sha }}"
          git push
        shell: bash
          
      # - name: Push changes
      #   uses: ad-action/push@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

  update-build-branch:
    runs-on: ubuntu-latest
    needs: [ bump-version ]
    steps:
      - name: Configure Git credentials
        run: |
          git config --global user.email "schyler.evans@gmail.com"
          git config --global user.name "Schyler Evans"

      - name: Checkout build branch
        uses: actions/checkout@v4
        with:
          ref: build
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Clear 
        run: rm -rf ./*

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Update build branch
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update build"
            git push
          fi
        shell: bash

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: [ update-build-branch ]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout build branch
        uses: actions/checkout@v4
        with:
          ref: build
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - uses: actions/deploy-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact: ${{ steps.upload-pages-artifact.outputs.artifacts }}
          skip-submodules: true
