name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

  test:
    needs: init
    runs-on: ubuntu-latest
    steps:

    - name: Run the tests
      run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    
    - name: Build
      run: npm run build
